/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerDashboardRouteImport } from './routes/seller.dashboard'
import { Route as FarmerDashboardRouteImport } from './routes/farmer.dashboard'
import { Route as FarmerCropScannerRouteImport } from './routes/farmer.crop-scanner'
import { Route as BuyerDashboardRouteImport } from './routes/buyer.dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerDashboardRoute = SellerDashboardRouteImport.update({
  id: '/seller/dashboard',
  path: '/seller/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerDashboardRoute = FarmerDashboardRouteImport.update({
  id: '/farmer/dashboard',
  path: '/farmer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerCropScannerRoute = FarmerCropScannerRouteImport.update({
  id: '/farmer/crop-scanner',
  path: '/farmer/crop-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerDashboardRoute = BuyerDashboardRouteImport.update({
  id: '/buyer/dashboard',
  path: '/buyer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/schemes': typeof SchemesRoute
  '/signup': typeof SignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/farmer/crop-scanner': typeof FarmerCropScannerRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/seller/dashboard': typeof SellerDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/schemes': typeof SchemesRoute
  '/signup': typeof SignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/farmer/crop-scanner': typeof FarmerCropScannerRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/seller/dashboard': typeof SellerDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/schemes': typeof SchemesRoute
  '/signup': typeof SignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/farmer/crop-scanner': typeof FarmerCropScannerRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/seller/dashboard': typeof SellerDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/login'
    | '/marketplace'
    | '/schemes'
    | '/signup'
    | '/admin/login'
    | '/buyer/dashboard'
    | '/farmer/crop-scanner'
    | '/farmer/dashboard'
    | '/seller/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/login'
    | '/marketplace'
    | '/schemes'
    | '/signup'
    | '/admin/login'
    | '/buyer/dashboard'
    | '/farmer/crop-scanner'
    | '/farmer/dashboard'
    | '/seller/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/login'
    | '/marketplace'
    | '/schemes'
    | '/signup'
    | '/admin/login'
    | '/buyer/dashboard'
    | '/farmer/crop-scanner'
    | '/farmer/dashboard'
    | '/seller/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  SchemesRoute: typeof SchemesRoute
  SignupRoute: typeof SignupRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BuyerDashboardRoute: typeof BuyerDashboardRoute
  FarmerCropScannerRoute: typeof FarmerCropScannerRoute
  FarmerDashboardRoute: typeof FarmerDashboardRoute
  SellerDashboardRoute: typeof SellerDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/dashboard': {
      id: '/seller/dashboard'
      path: '/seller/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof SellerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/dashboard': {
      id: '/farmer/dashboard'
      path: '/farmer/dashboard'
      fullPath: '/farmer/dashboard'
      preLoaderRoute: typeof FarmerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/crop-scanner': {
      id: '/farmer/crop-scanner'
      path: '/farmer/crop-scanner'
      fullPath: '/farmer/crop-scanner'
      preLoaderRoute: typeof FarmerCropScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/dashboard': {
      id: '/buyer/dashboard'
      path: '/buyer/dashboard'
      fullPath: '/buyer/dashboard'
      preLoaderRoute: typeof BuyerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  SchemesRoute: SchemesRoute,
  SignupRoute: SignupRoute,
  AdminLoginRoute: AdminLoginRoute,
  BuyerDashboardRoute: BuyerDashboardRoute,
  FarmerCropScannerRoute: FarmerCropScannerRoute,
  FarmerDashboardRoute: FarmerDashboardRoute,
  SellerDashboardRoute: SellerDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
